### PR TITLE
conditional rendering done

### PR DESCRIPTION
**Pull request by lcurtis4**
## What Changed 

1. Added a checkbox to the task card
2. Task list renders based on the "isComplete" property of a task. (when true- task does not appear on the list) 

## Steps to test 

1. git fetch --all 
2. git checkout lrc-isComplete
3. See that when a new task is created, the task card displays in taskList
4. See that a user has the affordance to delete a task
5. See that when the checkbox is clicked a task with the property "isCompleted" changes from false to true, in the database. 
6. When a task has the property "isCompleted" set to true, in the database, that task should not render on the dom.

### CODE REVIEW

**Review by Thomas88s — APPROVED** [review]
I saw it first hand

**Comment by Thomas88s** [comment]
👍

**Comment by JAndraeis53** [comment]
I saw it first

**Review by kor0sensei — APPROVED** [review]
👍

**Pull request merged**
